/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package andrewcoledaniel_monopoly;


import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.net.URL;
import java.util.Scanner;
import javax.sound.sampled.*;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dakim0069
 */
public class MainMenu extends javax.swing.JFrame {
    private TutorialMenu tutorial;
    private GameScreen gameScreen;
    private HighScoreMenu highScoreMenu;
    public int[] highscores = new int[5];
    public String[] date = new String[5];
    public MainMusic mainBgm;
    private Thread mainBgmThread;
    public static int limitedTurns;
    public static long limitedTime;
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        monopolyImage();
        readHighScore();
        mainBgm = new MainMusic();
        mainBgmThread = new Thread(mainBgm);
        mainBgmThread.start();
    }
    
    private void readHighScore()
    {
        InputStream inp = MainMenu.class.getResourceAsStream("saves/HighScores.txt");
        Scanner scan = new Scanner(inp);
        
        for(int i=0; i<5; i++)
        {
            highscores[i] = scan.nextInt();
            date[i] = scan.nextLine();
        }
    }
    
    private void monopolyImage()
    {
        
        Image img;
        
        //Title image
        URL urlMonopoly = GameScreen.class.getResource("saves/MonoPoly.png");
        ImageIcon mply = new ImageIcon(urlMonopoly);
        img = mply.getImage();
        mply = new ImageIcon(img.getScaledInstance(lblTitle.getWidth(), lblTitle.getHeight(), Image.SCALE_SMOOTH));
        lblTitle.setIcon(mply);
        
        //highscore button image
        btnHighScores.setOpaque(false);
        btnHighScores.setFocusPainted(false);
        btnHighScores.setBorderPainted(false);
        btnHighScores.setContentAreaFilled(false);
        btnHighScores.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        URL urlHighScore = GameScreen.class.getResource("saves/highScores.jpg");
        ImageIcon scores = new ImageIcon(urlHighScore);
        img = scores.getImage();
        scores = new ImageIcon(img.getScaledInstance(btnHighScores.getWidth(), btnHighScores.getHeight(), Image.SCALE_SMOOTH));
        btnHighScores.setIcon(scores);
        
        //new game button image
        btnHighScores.setBorder(null);
        URL urlNewGame = GameScreen.class.getResource("saves/newGame.png");
        ImageIcon newGame = new ImageIcon(urlNewGame);
        img = newGame.getImage();
        newGame = new ImageIcon(img.getScaledInstance(btnNewGame.getWidth(), btnNewGame.getHeight(), Image.SCALE_SMOOTH));
        btnNewGame.setIcon(newGame);
        
        btnLoadSave.setBorder(null);
        URL urlLoadSave = GameScreen.class.getResource("saves/loadSave.jpg");
        ImageIcon loadSave = new ImageIcon(urlLoadSave);
        img = loadSave.getImage();
        loadSave = new ImageIcon(img.getScaledInstance(btnLoadSave.getWidth(), btnLoadSave.getHeight(), Image.SCALE_SMOOTH));
        btnLoadSave.setIcon(loadSave);
        
        URL urlMoney = GameScreen.class.getResource("saves/street.jpg");
        ImageIcon money = new ImageIcon(urlMoney);
        img = money.getImage();
        money = new ImageIcon(img.getScaledInstance(lblBackground.getWidth(), lblBackground.getHeight(), Image.SCALE_SMOOTH));
        lblBackground.setIcon(money);
               
        btnTutorial.setOpaque(false);
        btnTutorial.setFocusPainted(false);
        btnTutorial.setBorderPainted(false);
        btnTutorial.setContentAreaFilled(false);
        btnTutorial.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        URL urlHelp = GameScreen.class.getResource("saves/tutorial.png");
        ImageIcon tutorial = new ImageIcon(urlHelp);
        img = tutorial.getImage();
        tutorial = new ImageIcon(img.getScaledInstance(btnTutorial.getWidth(), btnTutorial.getHeight(), Image.SCALE_SMOOTH));
        btnTutorial.setIcon(tutorial);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnNewGame = new javax.swing.JButton();
        btnTutorial = new javax.swing.JButton();
        btnHighScores = new javax.swing.JButton();
        btnLoadSave = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monopoly Menu");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlMain.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 14, 373, 100));

        btnNewGame.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNewGame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });
        pnlMain.add(btnNewGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 125, 40));

        btnTutorial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTutorial.setText("");
        btnTutorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutorialActionPerformed(evt);
            }
        });
        pnlMain.add(btnTutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 75, 75));
        btnTutorial.getAccessibleContext().setAccessibleName("");

        btnHighScores.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHighScores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHighScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHighScoresActionPerformed(evt);
            }
        });
        pnlMain.add(btnHighScores, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 249, 75, 75));

        btnLoadSave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLoadSave.setText("");
        btnLoadSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoadSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadSaveActionPerformed(evt);
            }
        });
        pnlMain.add(btnLoadSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 125, 40));
        pnlMain.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadSaveActionPerformed
        String saveFilePath = null;
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fileChooser.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            saveFilePath = fileChooser.getSelectedFile().getAbsolutePath();
        }
        File saveFile = new File(saveFilePath + "/MonopolySave.txt");

        try {
            FileInputStream in = new FileInputStream(saveFile);
            ObjectInputStream s = new ObjectInputStream(in);
            int gameMode = s.readInt();
            int currentTurn = s.readInt();
            int numPlayers = s.readInt();
            Player[] playerArray = (Player[]) s.readObject();
            mainBgm.musicOff();
            gameScreen = new GameScreen(this, gameMode, currentTurn, numPlayers, playerArray);
            gameScreen.setVisible(true);
            this.setVisible(false);
        } catch (NullPointerException | IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex, "File selection error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoadSaveActionPerformed

    private void btnHighScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighScoresActionPerformed
        if(highScoreMenu == null)
        {
            highScoreMenu = new HighScoreMenu(this);
        }
        highScoreMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHighScoresActionPerformed

    private void btnTutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutorialActionPerformed
        if(tutorial == null)
        {
            tutorial = new TutorialMenu(this);
        }
        tutorial.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTutorialActionPerformed

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        String[] gameOptions = {"limited turn", "limited time", "infinite"};
        String[] computerChoice = {"1 Computer", "2 Computers", "3 Computers"};
        int gameMode = JOptionPane.showOptionDialog(null, "Which mode do you want to play?", "Mode Selection", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, gameOptions , gameOptions[0]);

        String input = "";
        try {
            if(gameMode == 0){
                input = JOptionPane.showInputDialog("How many turns would you like to play?");
                limitedTurns = Integer.parseInt(input);
            } else if(gameMode == 1){
                input = JOptionPane.showInputDialog("How long would you like the game to be? (minute)");
                limitedTime = Long.parseLong(input);
            }
        }catch (NumberFormatException e) {
            input = null;
        }

        if(gameMode != -1 && input != null)
        {
            int numPlayers = JOptionPane.showOptionDialog(null, "How many opponents do you want to play against", "Computer Player Selection", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, computerChoice, computerChoice[0]);
            numPlayers += 2;
            if(numPlayers != -1)
            {
                mainBgm.musicOff();
                gameScreen = new GameScreen(this, gameMode, numPlayers);
                gameScreen.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_btnNewGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHighScores;
    private javax.swing.JButton btnLoadSave;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JButton btnTutorial;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}

class MainMusic implements Runnable {
    private Clip mainSong;
    
    @Override
    public void run() 
    {
        try{
            mainSong = AudioSystem.getClip();
            //Dubby Jinglefunk's Not So Silent Night by Speck (c) copyright 2021 Licensed under a Creative Commons Attribution Noncommercial  (3.0) license. http://dig.ccmixter.org/files/speck/64503 Ft: Admiral Bob, Martijn de Boer, airtone, Carosone
            AudioInputStream inputBgm = AudioSystem.getAudioInputStream(MainMusic.class.getResourceAsStream("saves/Dubby_Jinglefunk.wav"));   
            mainSong.open(inputBgm);
            mainSong.loop(Clip.LOOP_CONTINUOUSLY);
            this.musicOn();
            
        } catch (Exception e)
        {
            System.out.println(e);
        }
    }
    public void musicOff()
    {
        mainSong.stop();
    }
    
    public void musicOn()
    {
        mainSong.start();
    }
}
